//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitiy_proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityUrunEntities : DbContext
    {
        public EntityUrunEntities()
            : base("name=EntityUrunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategori_tablo> kategori_tablo { get; set; }
        public virtual DbSet<musteri_tablo> musteri_tablo { get; set; }
        public virtual DbSet<satis_tablo> satis_tablo { get; set; }
        public virtual DbSet<urun_tablo> urun_tablo { get; set; }
    
        public virtual ObjectResult<string> markagetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("markagetir");
        }
    }
}
