//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitiy_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis_tablo
    {
        public int satis_ID { get; set; }
        public Nullable<int> satis_urun { get; set; }
        public Nullable<int> satis_musteri { get; set; }
        public Nullable<decimal> satis_fiyat { get; set; }
        public Nullable<System.DateTime> satis_tarih { get; set; }
    
        public virtual musteri_tablo musteri_tablo { get; set; }
        public virtual urun_tablo urun_tablo { get; set; }
    }
}
