//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitiy_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class urun_tablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urun_tablo()
        {
            this.satis_tablo = new HashSet<satis_tablo>();
        }
    
        public int urun_ID { get; set; }
        public string urun_AD { get; set; }
        public string urun_marka { get; set; }
        public Nullable<int> urun_stok { get; set; }
        public Nullable<decimal> urun_fiyat { get; set; }
        public Nullable<bool> urun_durum { get; set; }
        public Nullable<int> urun_kategori { get; set; }
    
        public virtual kategori_tablo kategori_tablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_tablo> satis_tablo { get; set; }
    }
}
